resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final
resources:
- name: platform-automation
  type: pivnet
  source:
    product_slug: platform-automation
    api_token: ((pivnet_api_token))
- name: repo
  type: git
  source:
    uri: https://github.com/making/demo-prepare-tasks-with-secrets.git

jobs:
- name: test
  plan:
  - in_parallel: 
    - get: platform-automation-image
      resource: platform-automation
      params:
        globs:
        - "*image*.tgz"
        unpack: true
    - get: platform-automation-tasks
      resource: platform-automation
      params:
        globs:
        - "*tasks*.zip"
        unpack: true
  - get: repo
  - task: prepare-tasks-with-secrets
    image: platform-automation-image
    file: platform-automation-tasks/tasks/prepare-tasks-with-secrets.yml
    input_mapping:
      tasks: repo
      config: repo
    output_mapping:
      tasks: updated
    params:
      CONFIG_PATH: task
  - task: debug
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
          tag: bionic
      inputs:
      - name: updated
      run:
        path: bash
        args: 
        - -c
        - |
          cat updated/task/task.yml
  - task: demo-task
    image: platform-automation-image
    file: updated/task/task.yml
